INSERT INTO lookup (PK_LOOKUP, IS_ACTIVE, CODE, DESCR, LOOKUP_GROUP, NAME, ORDER_NO) VALUES
(2, 1, 'ADMIN', 'ADMIN', 'USER_ROLE', 'ADMIN', 1);
(3, 1, 'AUDITOR', 'AUDITOR', 'USER_ROLE', 'AUDITOR', 1),
(4, 1, 'PETUGAS_MONITOR', 'PETUGAS_MONITOR', 'USER_ROLE', 'PETUGAS_MONITOR', 1),
(5, 1, 'PUSBIN', 'PUSBIN', 'USER_ROLE', 'PUSBIN', 1),
(6, 1, 'UNIT_APIP', 'UNIT_APIP', 'USER_ROLE', 'UNIT_APIP', 1);
